/usr/bin/xrandr --output DisplayPort-2 --rotate right
/usr/bin/xmobar &
/usr/bin/stalonetray &
/usr/bin/nm-applet &
/usr/bin/firefox &
/usr/bin/google-chrome &
/usr/bin/liferea &
/usr/bin/xscreensaver -no-splash &
/usr/bin/unclutter &
/usr/bin/synergys &
/usr/bin/xsetwacom --set "Wacom Bamboo Connect Pen stylus" Rotate half &
/usr/bin/xsetwacom --set "Wacom Bamboo Connect Pen eraser" Rotate half &
/usr/bin/xsetwacom --set "Wacom Bamboo Connect Finger touch" Rotate half &
/usr/bin/xsetwacom --set "Wacom Bamboo Connect Finger pad" Rotate half &
/usr/libexec/polkit-gnome-authentication-agent-1 &
/usr/bin/xmonad
