- hosts: localhost
  vars:
    dotfiles_repo: "git@github.com:Marquis42/dotfiles.git"
    dotfiles_repo_local_destination: "~/src/dotfiles"
    dotfiles_files:
        - .bash_profile
        - .bashrc
        - .xsession
        - .stalonetrayrc
        - .xmobarrc
        - .xmonad/xmonad.hs
        - .vimrc.before.local
        - .config/powerline/config.json
  roles:
    - { role:  geerlingguy.dotfiles }
